"""empty message

Revision ID: 10243a168c8c
Revises: 40f69d3fd3fa
Create Date: 2019-03-06 16:15:26.654499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10243a168c8c'
down_revision = '40f69d3fd3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_company_name', table_name='companies')
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.create_index('ix_companies_company_name', 'companies', ['company_name'], unique=True)
    # ### end Alembic commands ###
