"""empty message

Revision ID: 18d63d7c4eb2
Revises: c63720f3ad17
Create Date: 2019-03-08 16:45:45.518227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d63d7c4eb2'
down_revision = 'c63720f3ad17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_portfolios_portfolio_name', table_name='portfolios')
    op.create_index(op.f('ix_portfolios_portfolio_name'), 'portfolios', ['portfolio_name'], unique=False)
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_index(op.f('ix_portfolios_portfolio_name'), table_name='portfolios')
    op.create_index('ix_portfolios_portfolio_name', 'portfolios', ['portfolio_name'], unique=True)
    op.drop_column('portfolios', 'user_id')
    # ### end Alembic commands ###
