"""empty message

Revision ID: 40f69d3fd3fa
Revises: e82e67625858
Create Date: 2019-03-06 15:52:40.975790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f69d3fd3fa'
down_revision = 'e82e67625858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_name', sa.String(length=256), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_portfolio_name'), 'portfolios', ['portfolio_name'], unique=False)
    op.add_column('companies', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('portfolio_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'companies', 'portfolios', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'portfolio_id')
    op.drop_column('companies', 'date_created')
    op.drop_index(op.f('ix_portfolios_portfolio_name'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
