"""empty message

Revision ID: 4ce21fb51a15
Revises: be3be7ae5ff9
Create Date: 2019-03-08 17:46:01.621437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce21fb51a15'
down_revision = 'be3be7ae5ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_hash', sa.String(length=256), nullable=False))
    op.drop_column('users', 'hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('users', 'pass_hash')
    # ### end Alembic commands ###
