"""empty message

Revision ID: b28510727dee
Revises: 4ce21fb51a15
Create Date: 2019-03-08 19:34:20.363069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28510727dee'
down_revision = '4ce21fb51a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_company_name', table_name='companies')
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    op.drop_index('ix_portfolios_portfolio_name', table_name='portfolios')
    op.create_index(op.f('ix_portfolios_portfolio_name'), 'portfolios', ['portfolio_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolios_portfolio_name'), table_name='portfolios')
    op.create_index('ix_portfolios_portfolio_name', 'portfolios', ['portfolio_name'], unique=False)
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.create_index('ix_companies_company_name', 'companies', ['company_name'], unique=False)
    # ### end Alembic commands ###
