"""empty message

Revision ID: be3be7ae5ff9
Revises: 18d63d7c4eb2
Create Date: 2019-03-08 17:42:47.112400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3be7ae5ff9'
down_revision = '18d63d7c4eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash', sa.String(length=256), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('users', 'hash')
    # ### end Alembic commands ###
