"""empty message

Revision ID: c81c6f1cc3ee
Revises: 10243a168c8c
Create Date: 2019-03-06 21:16:22.632263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81c6f1cc3ee'
down_revision = '10243a168c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portfolios_portfolio_name', table_name='portfolios')
    op.create_index(op.f('ix_portfolios_portfolio_name'), 'portfolios', ['portfolio_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolios_portfolio_name'), table_name='portfolios')
    op.create_index('ix_portfolios_portfolio_name', 'portfolios', ['portfolio_name'], unique=False)
    # ### end Alembic commands ###
