"""empty message

Revision ID: e82e67625858
Revises: 10880b0fb3fd
Create Date: 2019-03-05 18:11:37.521672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82e67625858'
down_revision = '10880b0fb3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_name', sa.String(length=256), nullable=True))
    op.add_column('companies', sa.Column('symbol', sa.String(length=12), nullable=True))
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.drop_index('ix_companies_name', table_name='companies')
    op.drop_column('companies', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_index('ix_companies_name', 'companies', ['name'], unique=True)
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_column('companies', 'symbol')
    op.drop_column('companies', 'company_name')
    # ### end Alembic commands ###
